# Generated by Django 5.0 on 2023-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titles', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
