# Generated by Django 5.0 on 2023-12-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titlesArticle', models.CharField(max_length=250)),
                ('descriptionArticle', models.TextField()),
                ('urlImageArticle', models.TextField()),
                ('createArticle', models.DateTimeField()),
                ('updateArticle', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Actu',
        ),
    ]
