# Generated by Django 5.0 on 2023-12-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actu', '0002_article_delete_actu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createArticle',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='descriptionArticle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='updateArticle',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='urlImageArticle',
            field=models.TextField(null=True),
        ),
    ]
